// DO NOT MODIFY -- THIS FILE WAS GENERATED BY `python3 final_generate_icons_h.py`

#ifndef __ICONS_H__
#define __ICONS_H__

#include <cstddef>

#include "icons_16x16.h"
#include "icons_24x24.h"
#include "icons_32x32.h"
#include "icons_48x48.h"
#include "icons_64x64.h"
#include "icons_96x96.h"
#include "icons_128x128.h"
#include "icons_160x160.h"
#include "icons_196x196.h"

typedef enum icon_name {
  battery_0_bar_0deg,
  battery_0_bar_90deg,
  battery_1_bar_0deg,
  battery_1_bar_90deg,
  battery_2_bar_0deg,
  battery_2_bar_90deg,
  battery_3_bar_0deg,
  battery_3_bar_90deg,
  battery_4_bar_0deg,
  battery_4_bar_90deg,
  battery_5_bar_0deg,
  battery_5_bar_90deg,
  battery_6_bar_0deg,
  battery_6_bar_90deg,
  battery_alert_0deg,
  battery_alert_90deg,
  battery_charging_full_0deg,
  battery_charging_full_90deg,
  battery_full_0deg,
  battery_full_90deg,
  error_icon,
  sync_problem,
  warning_icon,
  wi_cloudy,
  wi_day_cloudy,
  wi_day_rain,
  wi_day_showers,
  wi_day_sunny,
  wi_fog,
  wi_na,
  wi_night_alt_cloudy,
  wi_night_alt_rain,
  wi_night_alt_showers,
  wi_night_clear,
  wi_rain,
  wi_sleet,
  wi_snow,
  wi_sprinkle,
  wi_sunrise,
  wi_sunset,
  wi_thunderstorm,
  wifi,
  wifi_1_bar,
  wifi_2_bar,
  wifi_3_bar,
  wifi_off,
  wifi_x,
} icon_name_t;

constexpr const unsigned char* getBitmap(icon_name_t icon, size_t size)
{
  switch (icon) {
  case battery_0_bar_0deg:
    switch (size) {
    case 16: return battery_0_bar_0deg_16x16;
    case 24: return battery_0_bar_0deg_24x24;
    case 32: return battery_0_bar_0deg_32x32;
    case 48: return battery_0_bar_0deg_48x48;
    case 64: return battery_0_bar_0deg_64x64;
    case 96: return battery_0_bar_0deg_96x96;
    case 128: return battery_0_bar_0deg_128x128;
    case 160: return battery_0_bar_0deg_160x160;
    case 196: return battery_0_bar_0deg_196x196;
    default:
      return nullptr;
    }
  case battery_0_bar_90deg:
    switch (size) {
    case 16: return battery_0_bar_90deg_16x16;
    case 24: return battery_0_bar_90deg_24x24;
    case 32: return battery_0_bar_90deg_32x32;
    case 48: return battery_0_bar_90deg_48x48;
    case 64: return battery_0_bar_90deg_64x64;
    case 96: return battery_0_bar_90deg_96x96;
    case 128: return battery_0_bar_90deg_128x128;
    case 160: return battery_0_bar_90deg_160x160;
    case 196: return battery_0_bar_90deg_196x196;
    default:
      return nullptr;
    }
  case battery_1_bar_0deg:
    switch (size) {
    case 16: return battery_1_bar_0deg_16x16;
    case 24: return battery_1_bar_0deg_24x24;
    case 32: return battery_1_bar_0deg_32x32;
    case 48: return battery_1_bar_0deg_48x48;
    case 64: return battery_1_bar_0deg_64x64;
    case 96: return battery_1_bar_0deg_96x96;
    case 128: return battery_1_bar_0deg_128x128;
    case 160: return battery_1_bar_0deg_160x160;
    case 196: return battery_1_bar_0deg_196x196;
    default:
      return nullptr;
    }
  case battery_1_bar_90deg:
    switch (size) {
    case 16: return battery_1_bar_90deg_16x16;
    case 24: return battery_1_bar_90deg_24x24;
    case 32: return battery_1_bar_90deg_32x32;
    case 48: return battery_1_bar_90deg_48x48;
    case 64: return battery_1_bar_90deg_64x64;
    case 96: return battery_1_bar_90deg_96x96;
    case 128: return battery_1_bar_90deg_128x128;
    case 160: return battery_1_bar_90deg_160x160;
    case 196: return battery_1_bar_90deg_196x196;
    default:
      return nullptr;
    }
  case battery_2_bar_0deg:
    switch (size) {
    case 16: return battery_2_bar_0deg_16x16;
    case 24: return battery_2_bar_0deg_24x24;
    case 32: return battery_2_bar_0deg_32x32;
    case 48: return battery_2_bar_0deg_48x48;
    case 64: return battery_2_bar_0deg_64x64;
    case 96: return battery_2_bar_0deg_96x96;
    case 128: return battery_2_bar_0deg_128x128;
    case 160: return battery_2_bar_0deg_160x160;
    case 196: return battery_2_bar_0deg_196x196;
    default:
      return nullptr;
    }
  case battery_2_bar_90deg:
    switch (size) {
    case 16: return battery_2_bar_90deg_16x16;
    case 24: return battery_2_bar_90deg_24x24;
    case 32: return battery_2_bar_90deg_32x32;
    case 48: return battery_2_bar_90deg_48x48;
    case 64: return battery_2_bar_90deg_64x64;
    case 96: return battery_2_bar_90deg_96x96;
    case 128: return battery_2_bar_90deg_128x128;
    case 160: return battery_2_bar_90deg_160x160;
    case 196: return battery_2_bar_90deg_196x196;
    default:
      return nullptr;
    }
  case battery_3_bar_0deg:
    switch (size) {
    case 16: return battery_3_bar_0deg_16x16;
    case 24: return battery_3_bar_0deg_24x24;
    case 32: return battery_3_bar_0deg_32x32;
    case 48: return battery_3_bar_0deg_48x48;
    case 64: return battery_3_bar_0deg_64x64;
    case 96: return battery_3_bar_0deg_96x96;
    case 128: return battery_3_bar_0deg_128x128;
    case 160: return battery_3_bar_0deg_160x160;
    case 196: return battery_3_bar_0deg_196x196;
    default:
      return nullptr;
    }
  case battery_3_bar_90deg:
    switch (size) {
    case 16: return battery_3_bar_90deg_16x16;
    case 24: return battery_3_bar_90deg_24x24;
    case 32: return battery_3_bar_90deg_32x32;
    case 48: return battery_3_bar_90deg_48x48;
    case 64: return battery_3_bar_90deg_64x64;
    case 96: return battery_3_bar_90deg_96x96;
    case 128: return battery_3_bar_90deg_128x128;
    case 160: return battery_3_bar_90deg_160x160;
    case 196: return battery_3_bar_90deg_196x196;
    default:
      return nullptr;
    }
  case battery_4_bar_0deg:
    switch (size) {
    case 16: return battery_4_bar_0deg_16x16;
    case 24: return battery_4_bar_0deg_24x24;
    case 32: return battery_4_bar_0deg_32x32;
    case 48: return battery_4_bar_0deg_48x48;
    case 64: return battery_4_bar_0deg_64x64;
    case 96: return battery_4_bar_0deg_96x96;
    case 128: return battery_4_bar_0deg_128x128;
    case 160: return battery_4_bar_0deg_160x160;
    case 196: return battery_4_bar_0deg_196x196;
    default:
      return nullptr;
    }
  case battery_4_bar_90deg:
    switch (size) {
    case 16: return battery_4_bar_90deg_16x16;
    case 24: return battery_4_bar_90deg_24x24;
    case 32: return battery_4_bar_90deg_32x32;
    case 48: return battery_4_bar_90deg_48x48;
    case 64: return battery_4_bar_90deg_64x64;
    case 96: return battery_4_bar_90deg_96x96;
    case 128: return battery_4_bar_90deg_128x128;
    case 160: return battery_4_bar_90deg_160x160;
    case 196: return battery_4_bar_90deg_196x196;
    default:
      return nullptr;
    }
  case battery_5_bar_0deg:
    switch (size) {
    case 16: return battery_5_bar_0deg_16x16;
    case 24: return battery_5_bar_0deg_24x24;
    case 32: return battery_5_bar_0deg_32x32;
    case 48: return battery_5_bar_0deg_48x48;
    case 64: return battery_5_bar_0deg_64x64;
    case 96: return battery_5_bar_0deg_96x96;
    case 128: return battery_5_bar_0deg_128x128;
    case 160: return battery_5_bar_0deg_160x160;
    case 196: return battery_5_bar_0deg_196x196;
    default:
      return nullptr;
    }
  case battery_5_bar_90deg:
    switch (size) {
    case 16: return battery_5_bar_90deg_16x16;
    case 24: return battery_5_bar_90deg_24x24;
    case 32: return battery_5_bar_90deg_32x32;
    case 48: return battery_5_bar_90deg_48x48;
    case 64: return battery_5_bar_90deg_64x64;
    case 96: return battery_5_bar_90deg_96x96;
    case 128: return battery_5_bar_90deg_128x128;
    case 160: return battery_5_bar_90deg_160x160;
    case 196: return battery_5_bar_90deg_196x196;
    default:
      return nullptr;
    }
  case battery_6_bar_0deg:
    switch (size) {
    case 16: return battery_6_bar_0deg_16x16;
    case 24: return battery_6_bar_0deg_24x24;
    case 32: return battery_6_bar_0deg_32x32;
    case 48: return battery_6_bar_0deg_48x48;
    case 64: return battery_6_bar_0deg_64x64;
    case 96: return battery_6_bar_0deg_96x96;
    case 128: return battery_6_bar_0deg_128x128;
    case 160: return battery_6_bar_0deg_160x160;
    case 196: return battery_6_bar_0deg_196x196;
    default:
      return nullptr;
    }
  case battery_6_bar_90deg:
    switch (size) {
    case 16: return battery_6_bar_90deg_16x16;
    case 24: return battery_6_bar_90deg_24x24;
    case 32: return battery_6_bar_90deg_32x32;
    case 48: return battery_6_bar_90deg_48x48;
    case 64: return battery_6_bar_90deg_64x64;
    case 96: return battery_6_bar_90deg_96x96;
    case 128: return battery_6_bar_90deg_128x128;
    case 160: return battery_6_bar_90deg_160x160;
    case 196: return battery_6_bar_90deg_196x196;
    default:
      return nullptr;
    }
  case battery_alert_0deg:
    switch (size) {
    case 16: return battery_alert_0deg_16x16;
    case 24: return battery_alert_0deg_24x24;
    case 32: return battery_alert_0deg_32x32;
    case 48: return battery_alert_0deg_48x48;
    case 64: return battery_alert_0deg_64x64;
    case 96: return battery_alert_0deg_96x96;
    case 128: return battery_alert_0deg_128x128;
    case 160: return battery_alert_0deg_160x160;
    case 196: return battery_alert_0deg_196x196;
    default:
      return nullptr;
    }
  case battery_alert_90deg:
    switch (size) {
    case 16: return battery_alert_90deg_16x16;
    case 24: return battery_alert_90deg_24x24;
    case 32: return battery_alert_90deg_32x32;
    case 48: return battery_alert_90deg_48x48;
    case 64: return battery_alert_90deg_64x64;
    case 96: return battery_alert_90deg_96x96;
    case 128: return battery_alert_90deg_128x128;
    case 160: return battery_alert_90deg_160x160;
    case 196: return battery_alert_90deg_196x196;
    default:
      return nullptr;
    }
  case battery_charging_full_0deg:
    switch (size) {
    case 16: return battery_charging_full_0deg_16x16;
    case 24: return battery_charging_full_0deg_24x24;
    case 32: return battery_charging_full_0deg_32x32;
    case 48: return battery_charging_full_0deg_48x48;
    case 64: return battery_charging_full_0deg_64x64;
    case 96: return battery_charging_full_0deg_96x96;
    case 128: return battery_charging_full_0deg_128x128;
    case 160: return battery_charging_full_0deg_160x160;
    case 196: return battery_charging_full_0deg_196x196;
    default:
      return nullptr;
    }
  case battery_charging_full_90deg:
    switch (size) {
    case 16: return battery_charging_full_90deg_16x16;
    case 24: return battery_charging_full_90deg_24x24;
    case 32: return battery_charging_full_90deg_32x32;
    case 48: return battery_charging_full_90deg_48x48;
    case 64: return battery_charging_full_90deg_64x64;
    case 96: return battery_charging_full_90deg_96x96;
    case 128: return battery_charging_full_90deg_128x128;
    case 160: return battery_charging_full_90deg_160x160;
    case 196: return battery_charging_full_90deg_196x196;
    default:
      return nullptr;
    }
  case battery_full_0deg:
    switch (size) {
    case 16: return battery_full_0deg_16x16;
    case 24: return battery_full_0deg_24x24;
    case 32: return battery_full_0deg_32x32;
    case 48: return battery_full_0deg_48x48;
    case 64: return battery_full_0deg_64x64;
    case 96: return battery_full_0deg_96x96;
    case 128: return battery_full_0deg_128x128;
    case 160: return battery_full_0deg_160x160;
    case 196: return battery_full_0deg_196x196;
    default:
      return nullptr;
    }
  case battery_full_90deg:
    switch (size) {
    case 16: return battery_full_90deg_16x16;
    case 24: return battery_full_90deg_24x24;
    case 32: return battery_full_90deg_32x32;
    case 48: return battery_full_90deg_48x48;
    case 64: return battery_full_90deg_64x64;
    case 96: return battery_full_90deg_96x96;
    case 128: return battery_full_90deg_128x128;
    case 160: return battery_full_90deg_160x160;
    case 196: return battery_full_90deg_196x196;
    default:
      return nullptr;
    }
  case error_icon:
    switch (size) {
    case 16: return error_icon_16x16;
    case 24: return error_icon_24x24;
    case 32: return error_icon_32x32;
    case 48: return error_icon_48x48;
    case 64: return error_icon_64x64;
    case 96: return error_icon_96x96;
    case 128: return error_icon_128x128;
    case 160: return error_icon_160x160;
    case 196: return error_icon_196x196;
    default:
      return nullptr;
    }
  case sync_problem:
    switch (size) {
    case 16: return sync_problem_16x16;
    case 24: return sync_problem_24x24;
    case 32: return sync_problem_32x32;
    case 48: return sync_problem_48x48;
    case 64: return sync_problem_64x64;
    case 96: return sync_problem_96x96;
    case 128: return sync_problem_128x128;
    case 160: return sync_problem_160x160;
    case 196: return sync_problem_196x196;
    default:
      return nullptr;
    }
  case warning_icon:
    switch (size) {
    case 16: return warning_icon_16x16;
    case 24: return warning_icon_24x24;
    case 32: return warning_icon_32x32;
    case 48: return warning_icon_48x48;
    case 64: return warning_icon_64x64;
    case 96: return warning_icon_96x96;
    case 128: return warning_icon_128x128;
    case 160: return warning_icon_160x160;
    case 196: return warning_icon_196x196;
    default:
      return nullptr;
    }
  case wi_cloudy:
    switch (size) {
    case 16: return wi_cloudy_16x16;
    case 24: return wi_cloudy_24x24;
    case 32: return wi_cloudy_32x32;
    case 48: return wi_cloudy_48x48;
    case 64: return wi_cloudy_64x64;
    case 96: return wi_cloudy_96x96;
    case 128: return wi_cloudy_128x128;
    case 160: return wi_cloudy_160x160;
    case 196: return wi_cloudy_196x196;
    default:
      return nullptr;
    }
  case wi_day_cloudy:
    switch (size) {
    case 16: return wi_day_cloudy_16x16;
    case 24: return wi_day_cloudy_24x24;
    case 32: return wi_day_cloudy_32x32;
    case 48: return wi_day_cloudy_48x48;
    case 64: return wi_day_cloudy_64x64;
    case 96: return wi_day_cloudy_96x96;
    case 128: return wi_day_cloudy_128x128;
    case 160: return wi_day_cloudy_160x160;
    case 196: return wi_day_cloudy_196x196;
    default:
      return nullptr;
    }
  case wi_day_rain:
    switch (size) {
    case 16: return wi_day_rain_16x16;
    case 24: return wi_day_rain_24x24;
    case 32: return wi_day_rain_32x32;
    case 48: return wi_day_rain_48x48;
    case 64: return wi_day_rain_64x64;
    case 96: return wi_day_rain_96x96;
    case 128: return wi_day_rain_128x128;
    case 160: return wi_day_rain_160x160;
    case 196: return wi_day_rain_196x196;
    default:
      return nullptr;
    }
  case wi_day_showers:
    switch (size) {
    case 16: return wi_day_showers_16x16;
    case 24: return wi_day_showers_24x24;
    case 32: return wi_day_showers_32x32;
    case 48: return wi_day_showers_48x48;
    case 64: return wi_day_showers_64x64;
    case 96: return wi_day_showers_96x96;
    case 128: return wi_day_showers_128x128;
    case 160: return wi_day_showers_160x160;
    case 196: return wi_day_showers_196x196;
    default:
      return nullptr;
    }
  case wi_day_sunny:
    switch (size) {
    case 16: return wi_day_sunny_16x16;
    case 24: return wi_day_sunny_24x24;
    case 32: return wi_day_sunny_32x32;
    case 48: return wi_day_sunny_48x48;
    case 64: return wi_day_sunny_64x64;
    case 96: return wi_day_sunny_96x96;
    case 128: return wi_day_sunny_128x128;
    case 160: return wi_day_sunny_160x160;
    case 196: return wi_day_sunny_196x196;
    default:
      return nullptr;
    }
  case wi_fog:
    switch (size) {
    case 16: return wi_fog_16x16;
    case 24: return wi_fog_24x24;
    case 32: return wi_fog_32x32;
    case 48: return wi_fog_48x48;
    case 64: return wi_fog_64x64;
    case 96: return wi_fog_96x96;
    case 128: return wi_fog_128x128;
    case 160: return wi_fog_160x160;
    case 196: return wi_fog_196x196;
    default:
      return nullptr;
    }
  case wi_na:
    switch (size) {
    case 16: return wi_na_16x16;
    case 24: return wi_na_24x24;
    case 32: return wi_na_32x32;
    case 48: return wi_na_48x48;
    case 64: return wi_na_64x64;
    case 96: return wi_na_96x96;
    case 128: return wi_na_128x128;
    case 160: return wi_na_160x160;
    case 196: return wi_na_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_cloudy:
    switch (size) {
    case 16: return wi_night_alt_cloudy_16x16;
    case 24: return wi_night_alt_cloudy_24x24;
    case 32: return wi_night_alt_cloudy_32x32;
    case 48: return wi_night_alt_cloudy_48x48;
    case 64: return wi_night_alt_cloudy_64x64;
    case 96: return wi_night_alt_cloudy_96x96;
    case 128: return wi_night_alt_cloudy_128x128;
    case 160: return wi_night_alt_cloudy_160x160;
    case 196: return wi_night_alt_cloudy_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_rain:
    switch (size) {
    case 16: return wi_night_alt_rain_16x16;
    case 24: return wi_night_alt_rain_24x24;
    case 32: return wi_night_alt_rain_32x32;
    case 48: return wi_night_alt_rain_48x48;
    case 64: return wi_night_alt_rain_64x64;
    case 96: return wi_night_alt_rain_96x96;
    case 128: return wi_night_alt_rain_128x128;
    case 160: return wi_night_alt_rain_160x160;
    case 196: return wi_night_alt_rain_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_showers:
    switch (size) {
    case 16: return wi_night_alt_showers_16x16;
    case 24: return wi_night_alt_showers_24x24;
    case 32: return wi_night_alt_showers_32x32;
    case 48: return wi_night_alt_showers_48x48;
    case 64: return wi_night_alt_showers_64x64;
    case 96: return wi_night_alt_showers_96x96;
    case 128: return wi_night_alt_showers_128x128;
    case 160: return wi_night_alt_showers_160x160;
    case 196: return wi_night_alt_showers_196x196;
    default:
      return nullptr;
    }
  case wi_night_clear:
    switch (size) {
    case 16: return wi_night_clear_16x16;
    case 24: return wi_night_clear_24x24;
    case 32: return wi_night_clear_32x32;
    case 48: return wi_night_clear_48x48;
    case 64: return wi_night_clear_64x64;
    case 96: return wi_night_clear_96x96;
    case 128: return wi_night_clear_128x128;
    case 160: return wi_night_clear_160x160;
    case 196: return wi_night_clear_196x196;
    default:
      return nullptr;
    }
  case wi_rain:
    switch (size) {
    case 16: return wi_rain_16x16;
    case 24: return wi_rain_24x24;
    case 32: return wi_rain_32x32;
    case 48: return wi_rain_48x48;
    case 64: return wi_rain_64x64;
    case 96: return wi_rain_96x96;
    case 128: return wi_rain_128x128;
    case 160: return wi_rain_160x160;
    case 196: return wi_rain_196x196;
    default:
      return nullptr;
    }
  case wi_sleet:
    switch (size) {
    case 16: return wi_sleet_16x16;
    case 24: return wi_sleet_24x24;
    case 32: return wi_sleet_32x32;
    case 48: return wi_sleet_48x48;
    case 64: return wi_sleet_64x64;
    case 96: return wi_sleet_96x96;
    case 128: return wi_sleet_128x128;
    case 160: return wi_sleet_160x160;
    case 196: return wi_sleet_196x196;
    default:
      return nullptr;
    }
  case wi_snow:
    switch (size) {
    case 16: return wi_snow_16x16;
    case 24: return wi_snow_24x24;
    case 32: return wi_snow_32x32;
    case 48: return wi_snow_48x48;
    case 64: return wi_snow_64x64;
    case 96: return wi_snow_96x96;
    case 128: return wi_snow_128x128;
    case 160: return wi_snow_160x160;
    case 196: return wi_snow_196x196;
    default:
      return nullptr;
    }
  case wi_sprinkle:
    switch (size) {
    case 16: return wi_sprinkle_16x16;
    case 24: return wi_sprinkle_24x24;
    case 32: return wi_sprinkle_32x32;
    case 48: return wi_sprinkle_48x48;
    case 64: return wi_sprinkle_64x64;
    case 96: return wi_sprinkle_96x96;
    case 128: return wi_sprinkle_128x128;
    case 160: return wi_sprinkle_160x160;
    case 196: return wi_sprinkle_196x196;
    default:
      return nullptr;
    }
  case wi_sunrise:
    switch (size) {
    case 16: return wi_sunrise_16x16;
    case 24: return wi_sunrise_24x24;
    case 32: return wi_sunrise_32x32;
    case 48: return wi_sunrise_48x48;
    case 64: return wi_sunrise_64x64;
    case 96: return wi_sunrise_96x96;
    case 128: return wi_sunrise_128x128;
    case 160: return wi_sunrise_160x160;
    case 196: return wi_sunrise_196x196;
    default:
      return nullptr;
    }
  case wi_sunset:
    switch (size) {
    case 16: return wi_sunset_16x16;
    case 24: return wi_sunset_24x24;
    case 32: return wi_sunset_32x32;
    case 48: return wi_sunset_48x48;
    case 64: return wi_sunset_64x64;
    case 96: return wi_sunset_96x96;
    case 128: return wi_sunset_128x128;
    case 160: return wi_sunset_160x160;
    case 196: return wi_sunset_196x196;
    default:
      return nullptr;
    }
  case wi_thunderstorm:
    switch (size) {
    case 16: return wi_thunderstorm_16x16;
    case 24: return wi_thunderstorm_24x24;
    case 32: return wi_thunderstorm_32x32;
    case 48: return wi_thunderstorm_48x48;
    case 64: return wi_thunderstorm_64x64;
    case 96: return wi_thunderstorm_96x96;
    case 128: return wi_thunderstorm_128x128;
    case 160: return wi_thunderstorm_160x160;
    case 196: return wi_thunderstorm_196x196;
    default:
      return nullptr;
    }
  case wifi:
    switch (size) {
    case 16: return wifi_16x16;
    case 24: return wifi_24x24;
    case 32: return wifi_32x32;
    case 48: return wifi_48x48;
    case 64: return wifi_64x64;
    case 96: return wifi_96x96;
    case 128: return wifi_128x128;
    case 160: return wifi_160x160;
    case 196: return wifi_196x196;
    default:
      return nullptr;
    }
  case wifi_1_bar:
    switch (size) {
    case 16: return wifi_1_bar_16x16;
    case 24: return wifi_1_bar_24x24;
    case 32: return wifi_1_bar_32x32;
    case 48: return wifi_1_bar_48x48;
    case 64: return wifi_1_bar_64x64;
    case 96: return wifi_1_bar_96x96;
    case 128: return wifi_1_bar_128x128;
    case 160: return wifi_1_bar_160x160;
    case 196: return wifi_1_bar_196x196;
    default:
      return nullptr;
    }
  case wifi_2_bar:
    switch (size) {
    case 16: return wifi_2_bar_16x16;
    case 24: return wifi_2_bar_24x24;
    case 32: return wifi_2_bar_32x32;
    case 48: return wifi_2_bar_48x48;
    case 64: return wifi_2_bar_64x64;
    case 96: return wifi_2_bar_96x96;
    case 128: return wifi_2_bar_128x128;
    case 160: return wifi_2_bar_160x160;
    case 196: return wifi_2_bar_196x196;
    default:
      return nullptr;
    }
  case wifi_3_bar:
    switch (size) {
    case 16: return wifi_3_bar_16x16;
    case 24: return wifi_3_bar_24x24;
    case 32: return wifi_3_bar_32x32;
    case 48: return wifi_3_bar_48x48;
    case 64: return wifi_3_bar_64x64;
    case 96: return wifi_3_bar_96x96;
    case 128: return wifi_3_bar_128x128;
    case 160: return wifi_3_bar_160x160;
    case 196: return wifi_3_bar_196x196;
    default:
      return nullptr;
    }
  case wifi_off:
    switch (size) {
    case 16: return wifi_off_16x16;
    case 24: return wifi_off_24x24;
    case 32: return wifi_off_32x32;
    case 48: return wifi_off_48x48;
    case 64: return wifi_off_64x64;
    case 96: return wifi_off_96x96;
    case 128: return wifi_off_128x128;
    case 160: return wifi_off_160x160;
    case 196: return wifi_off_196x196;
    default:
      return nullptr;
    }
  case wifi_x:
    switch (size) {
    case 16: return wifi_x_16x16;
    case 24: return wifi_x_24x24;
    case 32: return wifi_x_32x32;
    case 48: return wifi_x_48x48;
    case 64: return wifi_x_64x64;
    case 96: return wifi_x_96x96;
    case 128: return wifi_x_128x128;
    case 160: return wifi_x_160x160;
    case 196: return wifi_x_196x196;
    default:
      return nullptr;
    }
  default:
    return nullptr;
  }
}

#endif